/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hzhang3' at '16-1-22 下午2:23' with Gradle 2.10
 *
 * @author hzhang3, @date 16-1-22 下午2:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
